# Generated by Django 4.2.5 on 2023-09-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='hamster.category'),
        ),
    ]
